apiVersion: v1
data:
  policy.csv: |
    p, role:master, applications, *, */*, allow
    p, role:master, repositories, *, *, allow
    p, role:master, projects, *, *, allow

    g, obo, role:master

    p, role:deployer, applications, get, */*, allow
    p, role:deployer, applications, override, */*, allow
    p, role:deployer, applications, sync, */*, allow

    g, deploy-agent, role:deployer
  policy.default: role:readonly
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2024-06-27T07:40:22Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "40510"
  uid: dee6f685-f064-460b-a4ac-b43cf52b3557
